In [1]:
import numpy as np

In [ ]:
#0-D Tensor/Scalor
a = np.array(1)
print(a)
print(a.shape)
print(a.ndim)

1
()
0


In [ ]:
#1-D Tensor/Vector
b = np.array([1, 2, 3, 4])
print(b)
print(b.shape)
print(b.ndim)

[1 2 3 4]
(4,)
1


In [ ]:
#2-D Tensor/Matrix
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [ ]:
#3-D Tensor
d = np.array([[[1, 2,3], [3, 4,5]], [[5, 6,5], [7, 8,9]]])
print(d) 
print(d.shape)
print(d.ndim)

[[[1 2 3]
  [3 4 5]]

 [[5 6 5]
  [7 8 9]]]
(2, 2, 3)
3


In [11]:
#4-D Tensor
e = np.array([[[[1, 2,3], [3, 4,5]], [[5, 6,7], [7, 8,9]]], [[[9, 10,11], [11, 12,13]], [[13, 14,15], [15, 16,17]]]])
print(e)
print(e.shape)
print(e.ndim)

[[[[ 1  2  3]
   [ 3  4  5]]

  [[ 5  6  7]
   [ 7  8  9]]]


 [[[ 9 10 11]
   [11 12 13]]

  [[13 14 15]
   [15 16 17]]]]
(2, 2, 2, 3)
4
