In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [ ]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
# .reshape(1,7) is used to convert the 1D array to 2D array because the model expects the input in 2D array format
# where 1 is the number of samples and 7 is the number of features

In [10]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [11]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\Kaushik Mandal\.virtualenvs\ClassicalML-_wR1sNSC\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [12]:
test_input_sex

array([[0., 1.]])

In [13]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [14]:
test_input_embarked

array([[0., 0., 1.]])

In [15]:
test_input_age = test_input[:,2].reshape(1,1)

- In the below concetanation step we  combined the transformed numerical and categorical features to create the final transformed training data in the same order as the original training data.

In [16]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [17]:
test_input_transformed.shape

(1, 10)

In [21]:
clf.predict(test_input_transformed)

array([0])

- So we did the same series of steps while predicting as well. As we did while training the model
- So if sometime you change the preprocessing steps in the training phase then you also have to change the same steps in the prediction phase in production. This is a major drawback of not using pipelines. If we were using pipelines then we would have done all these steps in a single line of code and we would not have to worry about changing the same steps in the prediction phase when we change the preprocessing steps in the training phase.